# Generated by Django 2.0.2 on 2019-10-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191015_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='votes_totla',
            new_name='votes_total',
        ),
    ]
